In [1]:
import numpy as np

**Ques 1** Write a function so that the columns of the output matrix are powers of the input vector.

In [2]:
def Power(vect, col, increasing):
    if increasing is True:
        arr = np.array([pow(x, i) for x in vect for i in range(col)])

    if increasing is False:
        arr = np.array([pow(x, len(vect)-i-1) for x in vect for i in range(col)])
    
    return arr.reshape(len(vect), col)

In [3]:
Power([1, 2, 3, 4], 4, True)

array([[ 1,  1,  1,  1],
       [ 1,  2,  4,  8],
       [ 1,  3,  9, 27],
       [ 1,  4, 16, 64]])

In [4]:
Power([1, 2, 3, 4], 4, False)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

**Ques 2** Write a function to find moving average in an array over a window: 

Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [5]:
def movingAvg(ls, k):
    arr = np.cumsum(ls, dtype=int)
    arr[k:] = arr[k:] - arr[:-k]
    return arr[k-1:]/k

In [6]:
movingAvg([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150], 3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])